### PR TITLE
charts updated

### PR DESCRIPTION
**Pull request by Priyaccuknox**
I have modified the charts according to the latest changes made in the main branch

### CODE REVIEW

**Comment by nyrahul** [comment]
Hey @Priyaccuknox , great to see this work ... 
Can you avoid copying the manifests and use symbolic links or some other way such that we can either use a single chart or multiple charts (using current way)?
Looking forward to reviewing this.

**Comment by Priyaccuknox** [comment]
> Hey @Priyaccuknox , great to see this work ... Can you avoid copying the manifests and use symbolic links or some other way such that we can either use a single chart or multiple charts (using current way)? Looking forward to reviewing this.

Sure @nyrahul Let me look into this.

**Comment by nyrahul** [comment]
Hey @Priyaccuknox , you are raising the PR to a different branch! You need to raise a PR to `main`. Secondly, please do not duplicate manifests. You can discuss this internally, if no one is clear about this in devops then we can discuss. CC: @SujithKasireddy

**Comment by Priyaccuknox** [comment]
> Hey @Priyaccuknox , you are raising the PR to a different branch! You need to raise a PR to `main`. Secondly, please do not duplicate manifests. You can discuss this internally, if no one is clear about this in devops then we can discuss. CC: @SujithKasireddy

Yes @nyrahul , based on @raviknox request, I raised the PR to a separate branch for testing instead of merging directly into the main branch. I will discuss the duplicate manifest issue internally as well.

**Review by SujithKasireddy — APPROVED** [review]

**Comment by Priyaccuknox** [comment]
Hi @nyrahul, 
I have updated the charts using symlinks as per the requirement in a separate branch [consol-charts](https://github.com/accuknox/accuknox-jobs/tree/consol-charts)
Once we test and confirm everything is working fine, we can merge it into the main branch.

**Pull request merged**
